/* generated by AutoFOCUS 3 (2.19.0) on Wed Nov 26 15:13:57 CET 2025 */
#ifndef __HEADER_Echo_ID_431_h
#define __HEADER_Echo_ID_431_h
#include "data_dictionary.h"

extern GEN_TYPE_boolean Impuls_Signal_ID_508;
 extern GEN_TYPE_double  distance_cm; // neu Code 
extern GEN_TYPE_boolean noval_Impuls_Signal_ID_508;

extern GEN_TYPE_double scratch_paper_distance;

extern GEN_TYPE_boolean Echo_Signal_ID_563;

extern GEN_TYPE_boolean noval_Echo_Signal_ID_563;

extern GEN_TYPE_boolean Runde_ID_872;

extern GEN_TYPE_boolean noval_Runde_ID_872;

extern GEN_TYPE_boolean TooClose_ID_699;

extern GEN_TYPE_boolean noval_TooClose_ID_699;

extern void clear_inputs_Echo_ID_431();

extern void clear_outputs_Echo_ID_431();

extern void init_Echo_ID_431();

extern void perform_step_Echo_ID_431();

#endif // __HEADER_Echo_ID_431_h
