/* generated by AutoFOCUS 3 (2.19.0) on Wed Nov 26 15:13:57 CET 2025 */
#ifndef __HEADER_Timer10_ID_579_h
#define __HEADER_Timer10_ID_579_h
#include "data_dictionary.h"

extern GEN_TYPE_boolean timeoutMessung_ID_587;

extern GEN_TYPE_boolean noval_timeoutMessung_ID_587;

extern void clear_inputs_Timer10_ID_579();

extern void clear_outputs_Timer10_ID_579();

extern void init_Timer10_ID_579();

extern void perform_step_Timer10_ID_579();

#endif // __HEADER_Timer10_ID_579_h
