/* generated by AutoFOCUS 3 (2.19.0) on Wed Nov 26 15:13:57 CET 2025 */
#ifndef __HEADER_TriggerFunk_ID_427_h
#define __HEADER_TriggerFunk_ID_427_h
#include "data_dictionary.h"

extern GEN_TYPE_boolean timeoutMessung_ID_589;

extern GEN_TYPE_boolean noval_timeoutMessung_ID_589;

extern GEN_TYPE_boolean Impuls_Signal_ID_690;

extern GEN_TYPE_boolean noval_Impuls_Signal_ID_690;

extern GEN_TYPE_boolean Runde_ID_870;

extern GEN_TYPE_boolean noval_Runde_ID_870;

extern void clear_inputs_TriggerFunk_ID_427();

extern void clear_outputs_TriggerFunk_ID_427();

extern void init_TriggerFunk_ID_427();

extern void perform_step_TriggerFunk_ID_427();

#endif // __HEADER_TriggerFunk_ID_427_h
