/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#include "inc-gen/Component_Architecture_ID_4.h"

void clear_inputs_Component_Architecture_ID_4(){
}

void clear_outputs_Component_Architecture_ID_4(){
}

void init_Component_Architecture_ID_4(){
	init_PowerUp_ID_80();
	init_WLAN_Modul_ID_140();
	init_WLAN_Chip_ID_227();
	init_Controller_ID_254();
	init_StartUP_ID_16();
	init_PowerUp_RoverHW_ID_98();
	init_HOTSPOT_HW_ID_194();
}

void perform_step_Component_Architecture_ID_4(){
	noval_PowerSwitch_ID_95 = noval_PowerSwitch_ID_43;
	if (!noval_PowerSwitch_ID_43) {
		PowerSwitch_ID_95 = PowerSwitch_ID_43;
	}
	
	noval_IP_Adresse_ID_242 = noval_IP_Adresse_ID_222;
	if (!noval_IP_Adresse_ID_222) {
		IP_Adresse_ID_242 = IP_Adresse_ID_222;
	}
	
	noval_Controller_ID_262 = noval_Controller_ID_249;
	if (!noval_Controller_ID_249) {
		Controller_ID_262 = Controller_ID_249;
	}
	
	noval_HOTSPOT_Signal_ID_164 = noval_HOTSPOT_Signal_ID_56;
	if (!noval_HOTSPOT_Signal_ID_56) {
		HOTSPOT_Signal_ID_164 = HOTSPOT_Signal_ID_56;
	}
	
	noval_AkkuButton_ID_88 = noval_AkkuButton_ID_75;
	if (!noval_AkkuButton_ID_75) {
		AkkuButton_ID_88 = AkkuButton_ID_75;
	}
	
	noval_SSID_ID_159 = noval_SSID_ID_217;
	if (!noval_SSID_ID_217) {
		SSID_ID_159 = SSID_ID_217;
	}
	
	noval_Passwort_ID_154 = noval_Passwort_ID_135;
	if (!noval_Passwort_ID_135) {
		Passwort_ID_154 = Passwort_ID_135;
	}
	
	perform_step_PowerUp_ID_80();
	noval_Signal_Power_ID_328 = noval_Signal_Power_ID_326;
	if (!noval_Signal_Power_ID_326) {
		Signal_Power_ID_328 = Signal_Power_ID_326;
	}
	
	noval_Signal_Power_ID_117 = noval_Signal_Power_ID_326;
	if (!noval_Signal_Power_ID_326) {
		Signal_Power_ID_117 = Signal_Power_ID_326;
	}
	
	perform_step_WLAN_Modul_ID_140();
	noval_HOTSPOT_Out_ID_235 = noval_HOTSPOT_Out_ID_233;
	if (!noval_HOTSPOT_Out_ID_233) {
		HOTSPOT_Out_ID_235 = HOTSPOT_Out_ID_233;
	}
	
	noval_HOTSPOT_Out_ID_202 = noval_HOTSPOT_Out_ID_233;
	if (!noval_HOTSPOT_Out_ID_233) {
		HOTSPOT_Out_ID_202 = HOTSPOT_Out_ID_233;
	}
	
	perform_step_WLAN_Chip_ID_227();
	perform_step_Controller_ID_254();
	noval_Controller_Out_ID_278 = noval_Controller_Out_ID_269;
	if (!noval_Controller_Out_ID_269) {
		Controller_Out_ID_278 = Controller_Out_ID_269;
	}
	
	perform_step_StartUP_ID_16();
	perform_step_PowerUp_RoverHW_ID_98();
	perform_step_HOTSPOT_HW_ID_194();
}
