/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#include "inc-gen/Controller_ID_254.h"

GEN_TYPE_boolean Controller_ID_262;

GEN_TYPE_boolean noval_Controller_ID_262;

GEN_TYPE_boolean Controller_Out_ID_269;

GEN_TYPE_boolean noval_Controller_Out_ID_269;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_398();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_402();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_409();

static GEN_TYPE_boolean fire_state_Init_ID_388();

static GEN_TYPE_boolean fire_state_State_ID_393();

static GEN_TYPE_boolean fire_state_State1_ID_404();

void clear_inputs_Controller_ID_254(){
	noval_Controller_ID_262 = GEN_TRUE;
}

void clear_outputs_Controller_ID_254(){
	noval_Controller_Out_ID_269 = GEN_TRUE;
}

void init_Controller_ID_254(){
	noval_Controller_Out_ID_269 = GEN_TRUE;
	current_state = 388;
}

void perform_step_Controller_ID_254(){
	clear_outputs_Controller_ID_254();
	if (current_state == 404) {
		fire_state_State1_ID_404();
	}
	else {
		if (current_state == 393) {
			fire_state_State_ID_393();
		}
		else {
			if (current_state == 388) {
				fire_state_Init_ID_388();
			}
		}
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_398(){
	if (GEN_TRUE) {
		current_state = 393;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_402(){
	if (GEN_TRUE) {
		current_state = 393;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_409(){
	if (!(noval_Controller_ID_262 == GEN_TRUE) && (noval_Controller_ID_262 == GEN_FALSE && Controller_ID_262 == GEN_TRUE)) {
		current_state = 404;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_state_Init_ID_388(){
	return fire_transition_Transition_Segment_ID_398();
}

static GEN_TYPE_boolean fire_state_State_ID_393(){
	if (!(fire_transition_Transition_Segment_ID_402() || fire_transition_Transition_Segment_ID_409())) {
		noval_Controller_Out_ID_269 = GEN_FALSE;
		Controller_Out_ID_269 = GEN_FALSE;
		
	}
	return GEN_TRUE;
}

static GEN_TYPE_boolean fire_state_State1_ID_404(){
	noval_Controller_Out_ID_269 = GEN_FALSE;
	Controller_Out_ID_269 = GEN_TRUE;
	
	return GEN_TRUE;
}
