/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#include "inc-gen/HOTSPOT_HW_ID_194.h"

GEN_TYPE_boolean HOTSPOT_Out_ID_202;

GEN_TYPE_boolean noval_HOTSPOT_Out_ID_202;

GEN_TYPE_boolean IP_Adresse_ID_222;

GEN_TYPE_boolean noval_IP_Adresse_ID_222;

void clear_inputs_HOTSPOT_HW_ID_194(){
	noval_HOTSPOT_Out_ID_202 = GEN_TRUE;
}

void clear_outputs_HOTSPOT_HW_ID_194(){
	noval_IP_Adresse_ID_222 = GEN_TRUE;
}

void init_HOTSPOT_HW_ID_194(){
	clear_outputs_HOTSPOT_HW_ID_194();
}

void perform_step_HOTSPOT_HW_ID_194(){
	clear_outputs_HOTSPOT_HW_ID_194();
}
