/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#include "inc-gen/PowerUp_ID_80.h"

GEN_TYPE_boolean AkkuButton_ID_88;

GEN_TYPE_boolean noval_AkkuButton_ID_88;

GEN_TYPE_boolean PowerSwitch_ID_95;

GEN_TYPE_boolean noval_PowerSwitch_ID_95;

GEN_TYPE_boolean Signal_Power_ID_326;

GEN_TYPE_boolean noval_Signal_Power_ID_326;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_295();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_318();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_322();

static GEN_TYPE_boolean fire_state_Init_ID_285();

static GEN_TYPE_boolean fire_state_Down_ID_290();

static GEN_TYPE_boolean fire_state_PowerOn_ID_313();

void clear_inputs_PowerUp_ID_80(){
	noval_AkkuButton_ID_88 = GEN_TRUE;
	noval_PowerSwitch_ID_95 = GEN_TRUE;
}

void clear_outputs_PowerUp_ID_80(){
	noval_Signal_Power_ID_326 = GEN_TRUE;
}

void init_PowerUp_ID_80(){
	noval_Signal_Power_ID_326 = GEN_TRUE;
	current_state = 285;
}

void perform_step_PowerUp_ID_80(){
	clear_outputs_PowerUp_ID_80();
	if (current_state == 313) {
		fire_state_PowerOn_ID_313();
	}
	else {
		if (current_state == 290) {
			fire_state_Down_ID_290();
		}
		else {
			if (current_state == 285) {
				fire_state_Init_ID_285();
			}
		}
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_295(){
	if (GEN_TRUE) {
		current_state = 290;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_318(){
	if (((noval_PowerSwitch_ID_95 == GEN_TRUE || noval_AkkuButton_ID_88 == GEN_TRUE) || !(noval_PowerSwitch_ID_95 == GEN_FALSE && PowerSwitch_ID_95 == GEN_TRUE)) || !(noval_AkkuButton_ID_88 == GEN_FALSE && AkkuButton_ID_88 == GEN_TRUE)) {
		current_state = 290;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_322(){
	if (((!(noval_PowerSwitch_ID_95 == GEN_TRUE) && !(noval_AkkuButton_ID_88 == GEN_TRUE)) && (noval_PowerSwitch_ID_95 == GEN_FALSE && PowerSwitch_ID_95 == GEN_TRUE)) && (noval_AkkuButton_ID_88 == GEN_FALSE && AkkuButton_ID_88 == GEN_TRUE)) {
		current_state = 313;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_state_Init_ID_285(){
	return fire_transition_Transition_Segment_ID_295();
}

static GEN_TYPE_boolean fire_state_Down_ID_290(){
	if (!(fire_transition_Transition_Segment_ID_318() || fire_transition_Transition_Segment_ID_322())) {
		noval_Signal_Power_ID_326 = GEN_FALSE;
		Signal_Power_ID_326 = GEN_FALSE;
		
	}
	return GEN_TRUE;
}

static GEN_TYPE_boolean fire_state_PowerOn_ID_313(){
	noval_Signal_Power_ID_326 = GEN_FALSE;
	Signal_Power_ID_326 = GEN_TRUE;
	
	return GEN_TRUE;
}
