/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#include "inc-gen/PowerUp_RoverHW_ID_98.h"

GEN_TYPE_boolean Signal_Power_ID_117;

GEN_TYPE_boolean noval_Signal_Power_ID_117;

void clear_inputs_PowerUp_RoverHW_ID_98(){
	noval_Signal_Power_ID_117 = GEN_TRUE;
}

void clear_outputs_PowerUp_RoverHW_ID_98(){
}

void init_PowerUp_RoverHW_ID_98(){
	clear_outputs_PowerUp_RoverHW_ID_98();
}

void perform_step_PowerUp_RoverHW_ID_98(){
	clear_outputs_PowerUp_RoverHW_ID_98();
}
