/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#include "inc-gen/StartUP_ID_16.h"

GEN_TYPE_boolean Controller_Out_ID_278;

GEN_TYPE_boolean noval_Controller_Out_ID_278;

GEN_TYPE_boolean PowerSwitch_ID_43;

GEN_TYPE_boolean noval_PowerSwitch_ID_43;

GEN_TYPE_boolean HOTSPOT_Signal_ID_56;

GEN_TYPE_boolean noval_HOTSPOT_Signal_ID_56;

GEN_TYPE_boolean AkkuButton_ID_75;

GEN_TYPE_boolean noval_AkkuButton_ID_75;

GEN_TYPE_boolean Passwort_ID_135;

GEN_TYPE_boolean noval_Passwort_ID_135;

GEN_TYPE_boolean SSID_ID_217;

GEN_TYPE_boolean noval_SSID_ID_217;

GEN_TYPE_boolean Controller_ID_249;

GEN_TYPE_boolean noval_Controller_ID_249;

void clear_inputs_StartUP_ID_16(){
	noval_Controller_Out_ID_278 = GEN_TRUE;
}

void clear_outputs_StartUP_ID_16(){
	noval_PowerSwitch_ID_43 = GEN_TRUE;
	noval_HOTSPOT_Signal_ID_56 = GEN_TRUE;
	noval_AkkuButton_ID_75 = GEN_TRUE;
	noval_Passwort_ID_135 = GEN_TRUE;
	noval_SSID_ID_217 = GEN_TRUE;
	noval_Controller_ID_249 = GEN_TRUE;
}

void init_StartUP_ID_16(){
	clear_outputs_StartUP_ID_16();
}

void perform_step_StartUP_ID_16(){
	clear_outputs_StartUP_ID_16();
}
