/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#include "inc-gen/WLAN_Modul_ID_140.h"

GEN_TYPE_boolean HOTSPOT_Signal_ID_164;

GEN_TYPE_boolean noval_HOTSPOT_Signal_ID_164;

GEN_TYPE_boolean SSID_ID_159;

GEN_TYPE_boolean noval_SSID_ID_159;

GEN_TYPE_boolean Passwort_ID_154;

GEN_TYPE_boolean noval_Passwort_ID_154;

GEN_TYPE_boolean Signal_Power_ID_328;

GEN_TYPE_boolean noval_Signal_Power_ID_328;

GEN_TYPE_boolean HOTSPOT_Out_ID_233;

GEN_TYPE_boolean noval_HOTSPOT_Out_ID_233;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_345();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_349();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_357();

static GEN_TYPE_boolean fire_state_Init_ID_333();

static GEN_TYPE_boolean fire_state_Down_ID_338();

static GEN_TYPE_boolean fire_state_Verbindung_Aktive_ID_353();

void clear_inputs_WLAN_Modul_ID_140(){
	noval_HOTSPOT_Signal_ID_164 = GEN_TRUE;
	noval_SSID_ID_159 = GEN_TRUE;
	noval_Passwort_ID_154 = GEN_TRUE;
	noval_Signal_Power_ID_328 = GEN_TRUE;
}

void clear_outputs_WLAN_Modul_ID_140(){
	noval_HOTSPOT_Out_ID_233 = GEN_TRUE;
}

void init_WLAN_Modul_ID_140(){
	noval_HOTSPOT_Out_ID_233 = GEN_TRUE;
	current_state = 333;
}

void perform_step_WLAN_Modul_ID_140(){
	clear_outputs_WLAN_Modul_ID_140();
	if (current_state == 353) {
		fire_state_Verbindung_Aktive_ID_353();
	}
	else {
		if (current_state == 338) {
			fire_state_Down_ID_338();
		}
		else {
			if (current_state == 333) {
				fire_state_Init_ID_333();
			}
		}
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_345(){
	if (GEN_TRUE) {
		current_state = 338;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_349(){
	if (!(noval_Signal_Power_ID_328 == GEN_FALSE && Signal_Power_ID_328 == GEN_TRUE)) {
		current_state = 338;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_357(){
	if (!(noval_Passwort_ID_154 == GEN_TRUE) && (!(noval_SSID_ID_159 == GEN_TRUE) && (!(noval_HOTSPOT_Signal_ID_164 == GEN_TRUE) && ((((noval_Signal_Power_ID_328 == GEN_FALSE && Signal_Power_ID_328 == GEN_TRUE) && (noval_Passwort_ID_154 == GEN_FALSE && Passwort_ID_154 == GEN_TRUE)) && (noval_SSID_ID_159 == GEN_FALSE && SSID_ID_159 == GEN_TRUE)) && (noval_HOTSPOT_Signal_ID_164 == GEN_FALSE && HOTSPOT_Signal_ID_164 == GEN_TRUE))))) {
		current_state = 353;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_state_Init_ID_333(){
	return fire_transition_Transition_Segment_ID_345();
}

static GEN_TYPE_boolean fire_state_Down_ID_338(){
	if (!(fire_transition_Transition_Segment_ID_349() || fire_transition_Transition_Segment_ID_357())) {
		noval_HOTSPOT_Out_ID_233 = GEN_FALSE;
		HOTSPOT_Out_ID_233 = GEN_FALSE;
		
	}
	return GEN_TRUE;
}

static GEN_TYPE_boolean fire_state_Verbindung_Aktive_ID_353(){
	noval_HOTSPOT_Out_ID_233 = GEN_FALSE;
	HOTSPOT_Out_ID_233 = GEN_TRUE;
	
	return GEN_TRUE;
}
