/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#include "inc-gen/WLAN_Chip_ID_227.h"

GEN_TYPE_boolean HOTSPOT_Out_ID_235;

GEN_TYPE_boolean noval_HOTSPOT_Out_ID_235;

GEN_TYPE_boolean IP_Adresse_ID_242;

GEN_TYPE_boolean noval_IP_Adresse_ID_242;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_371();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_378();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_382();

static GEN_TYPE_boolean fire_state_Init_ID_361();

static GEN_TYPE_boolean fire_state_s1_ID_366();

static GEN_TYPE_boolean fire_state_s2_ID_373();

void clear_inputs_WLAN_Chip_ID_227(){
	noval_HOTSPOT_Out_ID_235 = GEN_TRUE;
	noval_IP_Adresse_ID_242 = GEN_TRUE;
}

void clear_outputs_WLAN_Chip_ID_227(){
}

void init_WLAN_Chip_ID_227(){
	current_state = 361;
}

void perform_step_WLAN_Chip_ID_227(){
	clear_outputs_WLAN_Chip_ID_227();
	if (current_state == 373) {
		fire_state_s2_ID_373();
	}
	else {
		if (current_state == 366) {
			fire_state_s1_ID_366();
		}
		else {
			if (current_state == 361) {
				fire_state_Init_ID_361();
			}
		}
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_371(){
	if (GEN_TRUE) {
		current_state = 366;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_378(){
	if (noval_HOTSPOT_Out_ID_235 == GEN_FALSE && HOTSPOT_Out_ID_235 == GEN_TRUE) {
		current_state = 373;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_382(){
	if (noval_HOTSPOT_Out_ID_235 == GEN_FALSE && HOTSPOT_Out_ID_235 == GEN_FALSE) {
		current_state = 366;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_state_Init_ID_361(){
	return fire_transition_Transition_Segment_ID_371();
}

static GEN_TYPE_boolean fire_state_s1_ID_366(){
	return fire_transition_Transition_Segment_ID_378() || fire_transition_Transition_Segment_ID_382();
}

static GEN_TYPE_boolean fire_state_s2_ID_373(){
	return GEN_FALSE;
}
