/* generated by AutoFOCUS 3 (2.19.0) on Wed Nov 26 15:13:57 CET 2025 */
#include "Component_Architecture1_ID_420.h"

void clear_inputs_Component_Architecture1_ID_420(){
}

void clear_outputs_Component_Architecture1_ID_420(){
}

void init_Component_Architecture1_ID_420(){
	init_UltraschalSensor_HW_Componete_ID_435();
	init_Kontext_Rover_ID_704();
	init_TriggerFunk_ID_427();
	init_Echo_ID_431();
	init_Timer10_ID_579();
}

void perform_step_Component_Architecture1_ID_420(){
	noval_TooClose_ID_712 = noval_TooClose_ID_699;
	if (!noval_TooClose_ID_699) {
		TooClose_ID_712 = TooClose_ID_699;
	}
	
	noval_Echo_Signal_ID_563 = noval_Echo_Signal_ID_542;
	if (!noval_Echo_Signal_ID_542){
		Echo_Signal_ID_563 = Echo_Signal_ID_542;
	}
	
	noval_Impuls_Signal_ID_665 = noval_Impuls_Signal_ID_690;
	if (!noval_Impuls_Signal_ID_690) {
		Impuls_Signal_ID_665 = Impuls_Signal_ID_690;
	}
	
	noval_Runde_ID_872 = noval_Runde_ID_870;
	if (!noval_Runde_ID_870) {
		Runde_ID_872 = Runde_ID_870;
	}
	
	noval_Impuls_Signal_ID_508 = noval_Impuls_Signal_ID_690;
	if (!noval_Impuls_Signal_ID_690) {
		Impuls_Signal_ID_508 = Impuls_Signal_ID_690;
	}
	
	noval_timeoutMessung_ID_589 = noval_timeoutMessung_ID_587;
	if (!noval_timeoutMessung_ID_587) {
		timeoutMessung_ID_589 = timeoutMessung_ID_587;
	}
	
	perform_step_UltraschalSensor_HW_Componete_ID_435();
	perform_step_Kontext_Rover_ID_704();
	perform_step_TriggerFunk_ID_427();
	perform_step_Echo_ID_431();
	perform_step_Timer10_ID_579();
}
