/* generated by AutoFOCUS 3 (2.19.0) on Wed Nov 26 15:13:57 CET 2025 */
#include "Echo_ID_431.h"
#include <stdio.h>
#include <time.h>
#include <stdbool.h>

GEN_TYPE_boolean Impuls_Signal_ID_508;

GEN_TYPE_boolean noval_Impuls_Signal_ID_508;

GEN_TYPE_boolean Echo_Signal_ID_563;

GEN_TYPE_boolean noval_Echo_Signal_ID_563;

GEN_TYPE_boolean Runde_ID_872;

GEN_TYPE_boolean noval_Runde_ID_872;

GEN_TYPE_boolean TooClose_ID_699;

GEN_TYPE_boolean noval_TooClose_ID_699;

static GEN_TYPE_int current_state;

static GEN_TYPE_int echozeit;

static GEN_TYPE_int scratch_paper_echozeit;

static GEN_TYPE_int v2;

static GEN_TYPE_int scratch_paper_v2;

static GEN_TYPE_double distance;

 GEN_TYPE_double scratch_paper_distance;
 
static void copy_scratch_paper();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_528();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_817();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_821();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_828();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_832();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_837();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_856();

static GEN_TYPE_boolean fire_state_Init_ID_518();

static GEN_TYPE_boolean fire_state_Waiting_ID_523();

static GEN_TYPE_boolean fire_state_handle_Echo_ID_824();

void clear_inputs_Echo_ID_431(){
	noval_Impuls_Signal_ID_508 = true;
	noval_Echo_Signal_ID_563 = true;
	noval_Runde_ID_872 = true;
}

void clear_outputs_Echo_ID_431(){
	noval_TooClose_ID_699 = true;
}

void init_Echo_ID_431(){
	noval_TooClose_ID_699 = true;
	current_state = 518;
	echozeit = 0;
	scratch_paper_echozeit = 0;
	v2 = 0;
	scratch_paper_v2 = 0;
	distance = 0.0;
	scratch_paper_distance = 0.0;
}

void perform_step_Echo_ID_431(){




	clear_outputs_Echo_ID_431();

	if (current_state == 824) {
		
		fire_state_handle_Echo_ID_824();
	}
	else {
		if (current_state == 523) {
			//printf("fire_state_Init_ID_523");
			fire_state_Waiting_ID_523();
		}
		else {
			if (current_state == 518) {
			
				fire_state_Init_ID_518();
			}
		}
	}
	
	copy_scratch_paper();
	
}

static void copy_scratch_paper(){
	echozeit = scratch_paper_echozeit;
	v2 = scratch_paper_v2;
	distance = scratch_paper_distance;
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_528(){

	if (true) {
		
		current_state = 523;
		return true;
	}
	else {
		return false;
	}
}
// Note: Distance für die nur simulierte  Distance
static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_817(){
	if (distance != 0.0 && distance < 20.0) {
		//	printf("Distance Kliener\n ");
		noval_TooClose_ID_699 = false;
		TooClose_ID_699 = true;
		
		current_state = 523;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_821(){
	if (distance != 0.0 && distance > 20.0) {
	//	printf("Distance größer ");
		noval_TooClose_ID_699 = false;
		TooClose_ID_699 = false;
		
		current_state = 523;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_828(){
	if ((noval_Impuls_Signal_ID_508 == false && Impuls_Signal_ID_508 == true) && (noval_Runde_ID_872 == false && Runde_ID_872 == false)) {
		scratch_paper_echozeit = 0;


		scratch_paper_distance = 0.0;

		current_state = 824;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_832(){
	if (!(noval_Echo_Signal_ID_563 == false && Echo_Signal_ID_563 == true)) {
		scratch_paper_echozeit = echozeit + 1;
//printf("hier hängen ");
	
		current_state = 824;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_837(){
	if (!(noval_Echo_Signal_ID_563 == true) && (noval_Echo_Signal_ID_563 == false && Echo_Signal_ID_563 == true)) {
		//printf("Distance berechnet ");


		scratch_paper_distance =( (echozeit * 0.0343) * 0.5)*10; // 10u StepTime von dem Modell man kann das beliebig  festlegen für die Simulation 
 
		//printf("Distance= %f\n",scratch_paper_distance);
		//printf("Distance= %f",scratch_paper_distance);
		current_state = 523;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_856(){
	if ((noval_Impuls_Signal_ID_508 == false && Impuls_Signal_ID_508 == false) && (noval_Runde_ID_872 == false && Runde_ID_872 == true)) {
		//printf("TimeOut");


		current_state = 523;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Init_ID_518(){
	
	return fire_transition_Transition_Segment_ID_528();
}

static GEN_TYPE_boolean fire_state_Waiting_ID_523(){
	return fire_transition_Transition_Segment_ID_828() || (fire_transition_Transition_Segment_ID_817() || fire_transition_Transition_Segment_ID_821());
}

static GEN_TYPE_boolean fire_state_handle_Echo_ID_824(){
	return fire_transition_Transition_Segment_ID_832() || (fire_transition_Transition_Segment_ID_837() || fire_transition_Transition_Segment_ID_856());
}
