/* generated by AutoFOCUS 3 (2.19.0) on Wed Nov 26 15:13:57 CET 2025 */
#include "TriggerFunk_ID_427.h"
#include <stdio.h>
GEN_TYPE_boolean timeoutMessung_ID_589;

GEN_TYPE_boolean noval_timeoutMessung_ID_589;

GEN_TYPE_boolean Impuls_Signal_ID_690;

GEN_TYPE_boolean noval_Impuls_Signal_ID_690;

GEN_TYPE_boolean Runde_ID_870;

GEN_TYPE_boolean noval_Runde_ID_870;

static GEN_TYPE_int current_state;

static GEN_TYPE_int i;

static GEN_TYPE_int scratch_paper_i;

static GEN_TYPE_int v2;

static GEN_TYPE_int scratch_paper_v2;

static GEN_TYPE_boolean Runde_Internel;

static GEN_TYPE_boolean scratch_paper_Runde_Internel;

static void copy_scratch_paper();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_453();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_466();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_795();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_801();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_845();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_850();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_852();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_877();

static GEN_TYPE_boolean fire_state_Init_ID_443();

static GEN_TYPE_boolean fire_state_Timer6Start_ID_448();

static GEN_TYPE_boolean fire_state_StopTimer6_ID_461();

static GEN_TYPE_boolean fire_state_TriggerSignalSend_ID_839();

void clear_inputs_TriggerFunk_ID_427(){
	noval_timeoutMessung_ID_589 = true;
}

void clear_outputs_TriggerFunk_ID_427(){
	noval_Impuls_Signal_ID_690 = true;
	noval_Runde_ID_870 = true;
}

void init_TriggerFunk_ID_427(){
	noval_Impuls_Signal_ID_690 = true;
	noval_Runde_ID_870 = true;
	current_state = 443;
	i = 20;
	scratch_paper_i = 20;
	v2 = 0;
	scratch_paper_v2 = 0;
	Runde_Internel = false;
	scratch_paper_Runde_Internel = false;
}

void perform_step_TriggerFunk_ID_427(){
	clear_outputs_TriggerFunk_ID_427();
	if (current_state == 839) {
		fire_state_TriggerSignalSend_ID_839();
	}
	else {
		if (current_state == 461) {
			fire_state_StopTimer6_ID_461();
		}
		else {
			if (current_state == 448) {
				fire_state_Timer6Start_ID_448();
			}
			else {
				if (current_state == 443) {
					fire_state_Init_ID_443();
				}
			}
		}
	}
	copy_scratch_paper();
}

static void copy_scratch_paper(){
	i = scratch_paper_i;
	v2 = scratch_paper_v2;
	Runde_Internel = scratch_paper_Runde_Internel;
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_453(){
	if (true) {
		noval_Impuls_Signal_ID_690 = false;
		Impuls_Signal_ID_690 = false;
		
		noval_Runde_ID_870 = false;
		Runde_ID_870 = true;
		
		scratch_paper_Runde_Internel = true;
		current_state = 448;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_466(){
	if (noval_timeoutMessung_ID_589 == false && timeoutMessung_ID_589 == true) {
		noval_Impuls_Signal_ID_690 = false;
		Impuls_Signal_ID_690 = false;
		//printf("Die Trigger Signal Vorbereite");
		noval_Runde_ID_870 = false;
		Runde_ID_870 = true;
		
		scratch_paper_Runde_Internel = true;
		current_state = 461;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_795(){
	if (i < 20) {
		scratch_paper_i = i + 1;
		current_state = 461;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_801(){
	if (!(noval_timeoutMessung_ID_589 == false && timeoutMessung_ID_589 == true) && Runde_Internel == true) {
		noval_Impuls_Signal_ID_690 = false;
		Impuls_Signal_ID_690 = false;
		
		current_state = 448;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_845(){
	if (i >= 20) {
		//printf("Die ImpulsSignal ist gesendet und gewartet auf Echo oder TimeOut");
		scratch_paper_i = 0;
		noval_Impuls_Signal_ID_690 = false;
		Impuls_Signal_ID_690 = true;
		
		noval_Runde_ID_870 = false;
		Runde_ID_870 = false;
		
		scratch_paper_Runde_Internel = false;
		current_state = 839;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_850(){
	if (noval_timeoutMessung_ID_589 == false && timeoutMessung_ID_589 == false) {
		noval_Impuls_Signal_ID_690 = false;
		Impuls_Signal_ID_690 = true;
		
		current_state = 448;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_852(){
	if (noval_timeoutMessung_ID_589 == false && timeoutMessung_ID_589 == true) {
		noval_Impuls_Signal_ID_690 = false;
		Impuls_Signal_ID_690 = true;
		
		current_state = 839;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_877(){
	if (!(noval_timeoutMessung_ID_589 == false && timeoutMessung_ID_589 == true) && Runde_Internel == false) {
		noval_Impuls_Signal_ID_690 = false;
		Impuls_Signal_ID_690 = true;
		
		current_state = 448;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Init_ID_443(){
	return fire_transition_Transition_Segment_ID_453();
}

static GEN_TYPE_boolean fire_state_Timer6Start_ID_448(){
	return fire_transition_Transition_Segment_ID_466() || (fire_transition_Transition_Segment_ID_801() || fire_transition_Transition_Segment_ID_877());
}

static GEN_TYPE_boolean fire_state_StopTimer6_ID_461(){
	return fire_transition_Transition_Segment_ID_795() || fire_transition_Transition_Segment_ID_845();
}

static GEN_TYPE_boolean fire_state_TriggerSignalSend_ID_839(){
	return fire_transition_Transition_Segment_ID_852() || fire_transition_Transition_Segment_ID_850();
}
