/* generated by AutoFOCUS 3 (2.19.0) on Wed Nov 26 15:13:57 CET 2025 */
#include "UltraschalSensor_HW_Componete_ID_435.h"

GEN_TYPE_boolean Impuls_Signal_ID_665;

GEN_TYPE_boolean noval_Impuls_Signal_ID_665;

GEN_TYPE_boolean Echo_Signal_ID_542;

GEN_TYPE_boolean noval_Echo_Signal_ID_542;

void clear_inputs_UltraschalSensor_HW_Componete_ID_435(){
	noval_Impuls_Signal_ID_665 = true;
}

void clear_outputs_UltraschalSensor_HW_Componete_ID_435(){
	//noval_Echo_Signal_ID_542 = true;
}

void init_UltraschalSensor_HW_Componete_ID_435(){
	clear_outputs_UltraschalSensor_HW_Componete_ID_435();
}

void perform_step_UltraschalSensor_HW_Componete_ID_435(){
	clear_outputs_UltraschalSensor_HW_Componete_ID_435();
}
