/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#ifndef __HEADER_Component_Architecture_ID_4_h
#define __HEADER_Component_Architecture_ID_4_h
#include "inc-gen/data_dictionary.h"

#include "inc-gen/PowerUp_ID_80.h"

#include "inc-gen/WLAN_Modul_ID_140.h"

#include "inc-gen/WLAN_Chip_ID_227.h"

#include "inc-gen/Controller_ID_254.h"

#include "inc-gen/StartUP_ID_16.h"

#include "inc-gen/PowerUp_RoverHW_ID_98.h"

#include "inc-gen/HOTSPOT_HW_ID_194.h"

extern void clear_inputs_Component_Architecture_ID_4();

extern void clear_outputs_Component_Architecture_ID_4();

extern void init_Component_Architecture_ID_4();

extern void perform_step_Component_Architecture_ID_4();

#endif // __HEADER_Component_Architecture_ID_4_h
