/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#ifndef __HEADER_Controller_ID_254_h
#define __HEADER_Controller_ID_254_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean Controller_ID_262;

extern GEN_TYPE_boolean noval_Controller_ID_262;

extern GEN_TYPE_boolean Controller_Out_ID_269;

extern GEN_TYPE_boolean noval_Controller_Out_ID_269;

extern void clear_inputs_Controller_ID_254();

extern void clear_outputs_Controller_ID_254();

extern void init_Controller_ID_254();

extern void perform_step_Controller_ID_254();

#endif // __HEADER_Controller_ID_254_h
