/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#ifndef __HEADER_HOTSPOT_HW_ID_194_h
#define __HEADER_HOTSPOT_HW_ID_194_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean HOTSPOT_Out_ID_202;

extern GEN_TYPE_boolean noval_HOTSPOT_Out_ID_202;

extern GEN_TYPE_boolean IP_Adresse_ID_222;

extern GEN_TYPE_boolean noval_IP_Adresse_ID_222;

extern void clear_inputs_HOTSPOT_HW_ID_194();

extern void clear_outputs_HOTSPOT_HW_ID_194();

extern void init_HOTSPOT_HW_ID_194();

extern void perform_step_HOTSPOT_HW_ID_194();

#endif // __HEADER_HOTSPOT_HW_ID_194_h
