/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#ifndef __HEADER_PowerUp_RoverHW_ID_98_h
#define __HEADER_PowerUp_RoverHW_ID_98_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean Signal_Power_ID_117;

extern GEN_TYPE_boolean noval_Signal_Power_ID_117;

extern void clear_inputs_PowerUp_RoverHW_ID_98();

extern void clear_outputs_PowerUp_RoverHW_ID_98();

extern void init_PowerUp_RoverHW_ID_98();

extern void perform_step_PowerUp_RoverHW_ID_98();

#endif // __HEADER_PowerUp_RoverHW_ID_98_h
