/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#ifndef __HEADER_PowerUp_ID_80_h
#define __HEADER_PowerUp_ID_80_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean AkkuButton_ID_88;

extern GEN_TYPE_boolean noval_AkkuButton_ID_88;

extern GEN_TYPE_boolean PowerSwitch_ID_95;

extern GEN_TYPE_boolean noval_PowerSwitch_ID_95;

extern GEN_TYPE_boolean Signal_Power_ID_326;

extern GEN_TYPE_boolean noval_Signal_Power_ID_326;

extern void clear_inputs_PowerUp_ID_80();

extern void clear_outputs_PowerUp_ID_80();

extern void init_PowerUp_ID_80();

extern void perform_step_PowerUp_ID_80();

#endif // __HEADER_PowerUp_ID_80_h
