/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#ifndef __HEADER_StartUP_ID_16_h
#define __HEADER_StartUP_ID_16_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean Controller_Out_ID_278;

extern GEN_TYPE_boolean noval_Controller_Out_ID_278;

extern GEN_TYPE_boolean PowerSwitch_ID_43;

extern GEN_TYPE_boolean noval_PowerSwitch_ID_43;

extern GEN_TYPE_boolean HOTSPOT_Signal_ID_56;

extern GEN_TYPE_boolean noval_HOTSPOT_Signal_ID_56;

extern GEN_TYPE_boolean AkkuButton_ID_75;

extern GEN_TYPE_boolean noval_AkkuButton_ID_75;

extern GEN_TYPE_boolean Passwort_ID_135;

extern GEN_TYPE_boolean noval_Passwort_ID_135;

extern GEN_TYPE_boolean SSID_ID_217;

extern GEN_TYPE_boolean noval_SSID_ID_217;

extern GEN_TYPE_boolean Controller_ID_249;

extern GEN_TYPE_boolean noval_Controller_ID_249;

extern void clear_inputs_StartUP_ID_16();

extern void clear_outputs_StartUP_ID_16();

extern void init_StartUP_ID_16();

extern void perform_step_StartUP_ID_16();

#endif // __HEADER_StartUP_ID_16_h
