/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#ifndef __HEADER_WLAN_Modul_ID_140_h
#define __HEADER_WLAN_Modul_ID_140_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean HOTSPOT_Signal_ID_164;

extern GEN_TYPE_boolean noval_HOTSPOT_Signal_ID_164;

extern GEN_TYPE_boolean SSID_ID_159;

extern GEN_TYPE_boolean noval_SSID_ID_159;

extern GEN_TYPE_boolean Passwort_ID_154;

extern GEN_TYPE_boolean noval_Passwort_ID_154;

extern GEN_TYPE_boolean Signal_Power_ID_328;

extern GEN_TYPE_boolean noval_Signal_Power_ID_328;

extern GEN_TYPE_boolean HOTSPOT_Out_ID_233;

extern GEN_TYPE_boolean noval_HOTSPOT_Out_ID_233;

extern void clear_inputs_WLAN_Modul_ID_140();

extern void clear_outputs_WLAN_Modul_ID_140();

extern void init_WLAN_Modul_ID_140();

extern void perform_step_WLAN_Modul_ID_140();

#endif // __HEADER_WLAN_Modul_ID_140_h
