/* generated by AutoFOCUS 3 (2.28.0) on Mon Nov 17 11:01:19 CET 2025 */
#ifndef __HEADER_WLAN_Chip_ID_227_h
#define __HEADER_WLAN_Chip_ID_227_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean HOTSPOT_Out_ID_235;

extern GEN_TYPE_boolean noval_HOTSPOT_Out_ID_235;

extern GEN_TYPE_boolean IP_Adresse_ID_242;

extern GEN_TYPE_boolean noval_IP_Adresse_ID_242;

extern void clear_inputs_WLAN_Chip_ID_227();

extern void clear_outputs_WLAN_Chip_ID_227();

extern void init_WLAN_Chip_ID_227();

extern void perform_step_WLAN_Chip_ID_227();

#endif // __HEADER_WLAN_Chip_ID_227_h
