/* generated by AutoFOCUS 3 (2.28.0) on Wed Nov 19 11:31:54 CET 2025 */
#ifndef __HEADER_Component_Architecture1_ID_420_h
#define __HEADER_Component_Architecture1_ID_420_h
#include "data_dictionary.h"

#include "UltraschalSensor_HW_Componete_ID_435.h"

#include "Kontext_Rover_ID_704.h"

#include "TriggerFunk_ID_427.h"

#include "Echo_ID_431.h"

#include "Timer10_ID_579.h"

extern void clear_inputs_Component_Architecture1_ID_420();

extern void clear_outputs_Component_Architecture1_ID_420();

extern void init_Component_Architecture1_ID_420();

extern void perform_step_Component_Architecture1_ID_420();

#endif // __HEADER_Component_Architecture1_ID_420_h
