/* generated by AutoFOCUS 3 (2.28.0) on Wed Nov 19 11:31:54 CET 2025 */
#ifndef __HEADER_data_dictionary_h
#define __HEADER_data_dictionary_h
#if defined(__cplusplus)
typedef bool GEN_TYPE_boolean;
#else
typedef enum Enum_TYPE_boolean {
	GEN_FALSE = 0, GEN_TRUE = 1
} GEN_TYPE_boolean;
#endif

typedef int GEN_TYPE_int;

typedef double GEN_TYPE_double;

typedef enum Enum_MyEnum{
	First_ID_672 = 0,
	Second_ID_673 = 1
	#ifdef USE_GCC
} __attribute__ ((packed)) GEN_TYPE_MyEnum;
#else
} GEN_TYPE_MyEnum;
#endif


extern GEN_TYPE_MyEnum First();

extern GEN_TYPE_MyEnum Second();

extern char* MyEnumToString(GEN_TYPE_MyEnum value);

typedef struct Struct_MyStruct {
	GEN_TYPE_int  x;
	GEN_TYPE_int  y;
} GEN_TYPE_MyStruct;

#endif // __HEADER_data_dictionary_h
