/* generated by AutoFOCUS 3 (2.28.0) on Wed Nov 19 11:31:54 CET 2025 */
#ifndef __HEADER_Echo_ID_431_h
#define __HEADER_Echo_ID_431_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean Impuls_Signal_ID_508;

extern GEN_TYPE_boolean noval_Impuls_Signal_ID_508;

extern GEN_TYPE_boolean Echo_Signal_ID_563;

extern GEN_TYPE_boolean noval_Echo_Signal_ID_563;

extern GEN_TYPE_boolean TooClose_ID_699;

extern GEN_TYPE_boolean noval_TooClose_ID_699;

extern void clear_inputs_Echo_ID_431();

extern void clear_outputs_Echo_ID_431();

extern void init_Echo_ID_431();

extern void perform_step_Echo_ID_431();

#endif // __HEADER_Echo_ID_431_h
