/* generated by AutoFOCUS 3 (2.28.0) on Wed Nov 19 11:31:54 CET 2025 */
#ifndef __HEADER_Kontext_Rover_ID_704_h
#define __HEADER_Kontext_Rover_ID_704_h
#include "data_dictionary.h"

extern GEN_TYPE_boolean TooClose_ID_712;

extern GEN_TYPE_boolean noval_TooClose_ID_712;

extern void clear_inputs_Kontext_Rover_ID_704();

extern void clear_outputs_Kontext_Rover_ID_704();

extern void init_Kontext_Rover_ID_704();

extern void perform_step_Kontext_Rover_ID_704();

#endif // __HEADER_Kontext_Rover_ID_704_h
