/* generated by AutoFOCUS 3 (2.28.0) on Wed Nov 19 11:31:54 CET 2025 */
#ifndef __HEADER_UltraschalSensor_HW_Componete_ID_435_h
#define __HEADER_UltraschalSensor_HW_Componete_ID_435_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean Impuls_Signal_ID_665;

extern GEN_TYPE_boolean noval_Impuls_Signal_ID_665;

extern GEN_TYPE_boolean Echo_Signal_ID_542;

extern GEN_TYPE_boolean noval_Echo_Signal_ID_542;

extern void clear_inputs_UltraschalSensor_HW_Componete_ID_435();

extern void clear_outputs_UltraschalSensor_HW_Componete_ID_435();

extern void init_UltraschalSensor_HW_Componete_ID_435();

extern void perform_step_UltraschalSensor_HW_Componete_ID_435();

#endif // __HEADER_UltraschalSensor_HW_Componete_ID_435_h
