/* generated by AutoFOCUS 3 (2.28.0) on Wed Nov 19 11:31:54 CET 2025 */
#include "inc-gen/data_dictionary.h"

GEN_TYPE_MyEnum First(){
	return First_ID_672;
}

GEN_TYPE_MyEnum Second(){
	return Second_ID_673;
}

char* MyEnumToString(GEN_TYPE_MyEnum value){
	if (value == First_ID_672) {
		return "First()";
	}
	if (value == Second_ID_673) {
		return "Second()";
	}
	return "null";
	
}
