/* generated by AutoFOCUS 3 (2.28.0) on Wed Nov 19 11:31:54 CET 2025 */
#include "Echo_ID_431.h"

GEN_TYPE_boolean Impuls_Signal_ID_508;

GEN_TYPE_boolean noval_Impuls_Signal_ID_508;

GEN_TYPE_boolean Echo_Signal_ID_563;

GEN_TYPE_boolean noval_Echo_Signal_ID_563;

GEN_TYPE_boolean TooClose_ID_699;

GEN_TYPE_boolean noval_TooClose_ID_699;

static GEN_TYPE_int current_state;

static GEN_TYPE_int echozeit;

static GEN_TYPE_int scratch_paper_echozeit;

static GEN_TYPE_int v2;

static GEN_TYPE_int scratch_paper_v2;

static GEN_TYPE_double distance;

static GEN_TYPE_double scratch_paper_distance;

static void copy_scratch_paper();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_528();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_684();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_813();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_817();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_821();

static GEN_TYPE_boolean fire_state_Init_ID_518();

static GEN_TYPE_boolean fire_state_Waiting_ID_523();

void clear_inputs_Echo_ID_431(){
	noval_Impuls_Signal_ID_508 = true;
	noval_Echo_Signal_ID_563 = true;
}

void clear_outputs_Echo_ID_431(){
	noval_TooClose_ID_699 = true;
}

void init_Echo_ID_431(){
	noval_TooClose_ID_699 = true;
	current_state = 518;
	echozeit = 0;
	scratch_paper_echozeit = 0;
	v2 = 0;
	scratch_paper_v2 = 0;
	distance = 0.0;
	scratch_paper_distance = 0.0;
}

void perform_step_Echo_ID_431(){
	clear_outputs_Echo_ID_431();
	if (current_state == 523) {
		fire_state_Waiting_ID_523();
	}
	else {
		if (current_state == 518) {
			fire_state_Init_ID_518();
		}
	}
	copy_scratch_paper();
}

static void copy_scratch_paper(){
	echozeit = scratch_paper_echozeit;
	v2 = scratch_paper_v2;
	distance = scratch_paper_distance;
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_528(){
	if (true) {
		current_state = 523;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_684(){
	if (!(noval_Echo_Signal_ID_563 == false && Echo_Signal_ID_563 == true)) {
		scratch_paper_echozeit = echozeit + 1;
		current_state = 523;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_813(){
	if ((!(noval_Echo_Signal_ID_563 == true) && (noval_Echo_Signal_ID_563 == false && Echo_Signal_ID_563 == true)) && (noval_Impuls_Signal_ID_508 == false && Impuls_Signal_ID_508 == true)) {
		scratch_paper_distance = (echozeit * 3.43) * 0.5;
		current_state = 523;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_817(){
	if (distance != 0.0 && distance < 20.0) {
		noval_TooClose_ID_699 = false;
		TooClose_ID_699 = true;
		
		current_state = 523;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_821(){
	if (distance != 0.0 && distance > 20.0) {
		noval_TooClose_ID_699 = false;
		TooClose_ID_699 = false;
		
		current_state = 523;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Init_ID_518(){
	return fire_transition_Transition_Segment_ID_528();
}

static GEN_TYPE_boolean fire_state_Waiting_ID_523(){
	return fire_transition_Transition_Segment_ID_684() || (fire_transition_Transition_Segment_ID_813() || (fire_transition_Transition_Segment_ID_817() || fire_transition_Transition_Segment_ID_821()));
}
