/* generated by AutoFOCUS 3 (2.28.0) on Wed Nov 19 11:31:54 CET 2025 */
#include "Kontext_Rover_ID_704.h"

GEN_TYPE_boolean TooClose_ID_712;

GEN_TYPE_boolean noval_TooClose_ID_712;

void clear_inputs_Kontext_Rover_ID_704(){
	noval_TooClose_ID_712 = true;
}

void clear_outputs_Kontext_Rover_ID_704(){
}

void init_Kontext_Rover_ID_704(){
	clear_outputs_Kontext_Rover_ID_704();
}

void perform_step_Kontext_Rover_ID_704(){
	clear_outputs_Kontext_Rover_ID_704();
}
