/* generated by AutoFOCUS 3 (2.28.0) on Wed Nov 19 11:31:54 CET 2025 */
#include "Timer10_ID_579.h"

GEN_TYPE_boolean timeoutMessung_ID_587;

GEN_TYPE_boolean noval_timeoutMessung_ID_587;

static GEN_TYPE_int current_state;

static GEN_TYPE_int i;

static GEN_TYPE_int scratch_paper_i;

static GEN_TYPE_int v3;

static GEN_TYPE_int scratch_paper_v3;

static GEN_TYPE_int v2;

static GEN_TYPE_int scratch_paper_v2;

static GEN_TYPE_int v4;

static GEN_TYPE_int scratch_paper_v4;

static void copy_scratch_paper();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_735();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_739();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_746();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_750();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_758();

static GEN_TYPE_boolean fire_state_init_ID_727();

static GEN_TYPE_boolean fire_state_Conter_Timer_10_ID_730();

static GEN_TYPE_boolean fire_state_State_ID_742();

void clear_inputs_Timer10_ID_579(){
}

void clear_outputs_Timer10_ID_579(){
	noval_timeoutMessung_ID_587 = GEN_TRUE;
}

void init_Timer10_ID_579(){
	noval_timeoutMessung_ID_587 = GEN_TRUE;
	current_state = 727;
	i = 0;
	scratch_paper_i = 0;
	v3 = 0;
	scratch_paper_v3 = 0;
	v2 = 0;
	scratch_paper_v2 = 0;
	v4 = 0;
	scratch_paper_v4 = 0;
}

void perform_step_Timer10_ID_579(){
	clear_outputs_Timer10_ID_579();
	if (current_state == 742) {
		fire_state_State_ID_742();
	}
	else {
		if (current_state == 730) {
			fire_state_Conter_Timer_10_ID_730();
		}
		else {
			if (current_state == 727) {
				fire_state_init_ID_727();
			}
		}
	}
	copy_scratch_paper();
}

static void copy_scratch_paper(){
	i = scratch_paper_i;
	v3 = scratch_paper_v3;
	v2 = scratch_paper_v2;
	v4 = scratch_paper_v4;
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_735(){
	if (true) {
		scratch_paper_v2 = 0;
		noval_timeoutMessung_ID_587 = GEN_FALSE;
		timeoutMessung_ID_587 = GEN_TRUE;
		
		current_state = 730;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_739(){
	if (true) {
		scratch_paper_v2 = v2 + 1;
		noval_timeoutMessung_ID_587 = GEN_FALSE;
		timeoutMessung_ID_587 = GEN_TRUE;
		
		current_state = 730;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_746(){
	if (v2 == 100) {
		noval_timeoutMessung_ID_587 = GEN_FALSE;
		timeoutMessung_ID_587 = GEN_FALSE;
		
		scratch_paper_v2 = 0;
		current_state = 742;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_750(){
	if (v4 == 100) {
		noval_timeoutMessung_ID_587 = GEN_FALSE;
		timeoutMessung_ID_587 = GEN_TRUE;
		
		scratch_paper_v4 = 0;
		current_state = 730;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_758(){
	if (true) {
		scratch_paper_v4 = v4 + 1;
		noval_timeoutMessung_ID_587 = GEN_FALSE;
		timeoutMessung_ID_587 = GEN_FALSE;
		
		current_state = 742;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_state_init_ID_727(){
	return fire_transition_Transition_Segment_ID_735();
}

static GEN_TYPE_boolean fire_state_Conter_Timer_10_ID_730(){
	return fire_transition_Transition_Segment_ID_739() || fire_transition_Transition_Segment_ID_746();
}

static GEN_TYPE_boolean fire_state_State_ID_742(){
	if (!(fire_transition_Transition_Segment_ID_750() || fire_transition_Transition_Segment_ID_758())) {
		noval_timeoutMessung_ID_587 = GEN_FALSE;
		timeoutMessung_ID_587 = GEN_FALSE;
		
	}
	return GEN_TRUE;
}
