/* generated by AutoFOCUS 3 (2.28.0) on Wed Nov 19 11:31:54 CET 2025 */
#include "TriggerFunk_ID_427.h"

GEN_TYPE_boolean timeoutMessung_ID_589;

GEN_TYPE_boolean noval_timeoutMessung_ID_589;

GEN_TYPE_boolean Impuls_Signal_ID_690;

GEN_TYPE_boolean noval_Impuls_Signal_ID_690;

static GEN_TYPE_int current_state;

static GEN_TYPE_int i;

static GEN_TYPE_int scratch_paper_i;

static GEN_TYPE_int v2;

static GEN_TYPE_int scratch_paper_v2;

static void copy_scratch_paper();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_453();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_466();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_514();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_795();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_801();

static GEN_TYPE_boolean fire_state_Init_ID_443();

static GEN_TYPE_boolean fire_state_Timer6Start_ID_448();

static GEN_TYPE_boolean fire_state_StopTimer6_ID_461();

void clear_inputs_TriggerFunk_ID_427(){
	noval_timeoutMessung_ID_589 = GEN_TRUE;
}

void clear_outputs_TriggerFunk_ID_427(){
	noval_Impuls_Signal_ID_690 = GEN_TRUE;
}

void init_TriggerFunk_ID_427(){
	noval_Impuls_Signal_ID_690 = GEN_TRUE;
	current_state = 443;
	i = 20;
	scratch_paper_i = 20;
	v2 = 0;
	scratch_paper_v2 = 0;
}

void perform_step_TriggerFunk_ID_427(){
	clear_outputs_TriggerFunk_ID_427();
	if (current_state == 461) {
		fire_state_StopTimer6_ID_461();
	}
	else {
		if (current_state == 448) {
			fire_state_Timer6Start_ID_448();
		}
		else {
			if (current_state == 443) {
				fire_state_Init_ID_443();
			}
		}
	}
	copy_scratch_paper();
}

static void copy_scratch_paper(){
	i = scratch_paper_i;
	v2 = scratch_paper_v2;
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_453(){
	if (true) {
		current_state = 448;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_466(){
	if (noval_timeoutMessung_ID_589 == GEN_FALSE && timeoutMessung_ID_589 == GEN_TRUE) {
		noval_Impuls_Signal_ID_690 = GEN_FALSE;
		Impuls_Signal_ID_690 = GEN_TRUE;
		
		current_state = 461;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_514(){
	if (noval_timeoutMessung_ID_589 == GEN_FALSE && timeoutMessung_ID_589 == GEN_FALSE) {
		noval_Impuls_Signal_ID_690 = GEN_FALSE;
		Impuls_Signal_ID_690 = GEN_FALSE;
		
		current_state = 448;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_795(){
	if (!(noval_timeoutMessung_ID_589 == GEN_FALSE && timeoutMessung_ID_589 == GEN_FALSE)) {
		noval_Impuls_Signal_ID_690 = GEN_FALSE;
		Impuls_Signal_ID_690 = GEN_TRUE;
		
		current_state = 461;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_801(){
	if (!(noval_timeoutMessung_ID_589 == GEN_FALSE && timeoutMessung_ID_589 == GEN_TRUE)) {
		noval_Impuls_Signal_ID_690 = GEN_FALSE;
		Impuls_Signal_ID_690 = GEN_FALSE;
		
		current_state = 448;
		return GEN_TRUE;
	}
	else {
		return GEN_FALSE;
	}
}

static GEN_TYPE_boolean fire_state_Init_ID_443(){
	return fire_transition_Transition_Segment_ID_453();
}

static GEN_TYPE_boolean fire_state_Timer6Start_ID_448(){
	return fire_transition_Transition_Segment_ID_466() || fire_transition_Transition_Segment_ID_801();
}

static GEN_TYPE_boolean fire_state_StopTimer6_ID_461(){
	if (!(fire_transition_Transition_Segment_ID_514() || fire_transition_Transition_Segment_ID_795())) {
		noval_Impuls_Signal_ID_690 = GEN_FALSE;
		Impuls_Signal_ID_690 = GEN_TRUE;
		
	}
	return GEN_TRUE;
}
